### PR TITLE
Fixes broken links in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by measutosh**
## Description

Updated 3 broken links for - coding style, commit message, submitting a PR

## Related Issue(s)

Fixes #2845

## Release Notes

```release-note
   NONE
```

## Documentation

Fixes this issue which I had raised[#2845](https://github.com/gitpod-io/website/issues/2845)

### CODE REVIEW

**Comment by axonasif** [comment]
Hi @measutosh, thanks for the fixes! We had a recent docs restructuring, maybe these links were missed out to be redirected.

**Comment by measutosh** [comment]
> Hi @measutosh, thanks for the fixes! We had a recent docs restructuring, maybe these links were missed out to be redirected.

no issues @axonasif , I hope the corrections are fine and you can merge it.

And could you please assign this to me and see the description of the linked issue, there I have left few more requests

**Comment by measutosh** [comment]
Hi @axonasif , @pawlean , could you tell me why it got closed, I thought most of the things were correct at their own place

**Comment by axonasif** [comment]
@measutosh it was a mistake as your PR was linked on https://github.com/gitpod-io/website/pull/2846 as a reason, could you please create the PR again?

**Pull request closed without merging**
